# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(295, 218)
        Form.setMinimumSize(QtCore.QSize(295, 218))
        Form.setMaximumSize(QtCore.QSize(295, 218))
        Form.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 50, 161, 21))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.account = QtWidgets.QLineEdit(Form)
        self.account.setGeometry(QtCore.QRect(70, 90, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.account.setFont(font)
        self.account.setObjectName("account")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 90, 41, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(70, 130, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.password.setFont(font)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 31, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loginBtn = QtWidgets.QPushButton(Form)
        self.loginBtn.setGeometry(QtCore.QRect(110, 180, 81, 31))
        self.loginBtn.setObjectName("loginBtn")
        self.tip = QtWidgets.QLabel(Form)
        self.tip.setGeometry(QtCore.QRect(40, 160, 231, 21))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        self.tip.setFont(font)
        self.tip.setText("")
        self.tip.setAlignment(QtCore.Qt.AlignCenter)
        self.tip.setObjectName("tip")
        self.exitBtn = QtWidgets.QPushButton(Form)
        self.exitBtn.setGeometry(QtCore.QRect(270, 0, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        self.exitBtn.setFont(font)
        self.exitBtn.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 85, 0);")
        self.exitBtn.setFlat(True)
        self.exitBtn.setObjectName("exitBtn")
        self.logo = QtWidgets.QLabel(Form)
        self.logo.setGeometry(QtCore.QRect(0, 0, 81, 31))
        self.logo.setText("")
        self.logo.setScaledContents(False)
        self.logo.setObjectName("logo")

        self.retranslateUi(Form)
        self.loginBtn.clicked.connect(Form.loginEvent)
        self.exitBtn.clicked.connect(Form.closeEvent)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "待办任务提醒小程序"))
        self.label_3.setText(_translate("Form", "待办任务提醒小程序"))
        self.label.setText(_translate("Form", "帐号："))
        self.label_2.setText(_translate("Form", "密码："))
        self.loginBtn.setText(_translate("Form", "登录"))
        self.exitBtn.setText(_translate("Form", "×"))
