# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NotifyUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(197, 101)
        Dialog.setMinimumSize(QtCore.QSize(197, 101))
        Dialog.setMaximumSize(QtCore.QSize(197, 101))
        self.notify = QtWidgets.QLabel(Dialog)
        self.notify.setGeometry(QtCore.QRect(20, 20, 161, 61))
        self.notify.setMinimumSize(QtCore.QSize(0, 0))
        self.notify.setMaximumSize(QtCore.QSize(230, 100))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.notify.setFont(font)
        self.notify.setText("")
        self.notify.setObjectName("notify")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "待办任务消息"))
